NAME = client

.PHONY: all

all:
	echo -e "\033[40;32m[BEGIN] Compile client makefile [BEGIN]\033[0m";
	make -C src -j 16;
	echo -e "\033[40;32m[END] Compile client makefile [END]\033[0m";

clean:
	make -C src clean
