.PHONY: all

all:
	echo -e "\033[40;32m[BEGIN] Compile hnmj-server makefile [BEGIN]\033[0m";
	make -C src -j 16;
	echo -e "\033[40;32m[END] Compile hnmj-server makefile [END]\033[0m";

clean:
	make -C src clean
